name: Test

on: [push, pull_request]

jobs:
  test:
    name: Check that the project passes the tests & can be built
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Pack
        run: npm pack --dry-run
