name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        version: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]
        os: [ubuntu-latest, windows-latest]
    name: Check that the project is working on ${{ matrix.version }} for ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Audit
        run: npm audit

      - name: Pack
        run: npm pack --dry-run
